name:                Snippetbox
version:             0.1.0.0
github:              "githubuser/Snippetbox"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2024 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/Snippetbox#readme>

dependencies:
- base >= 4.7 && < 5
- classy-prelude
- text
- containers
- time
- mtl
- scotty
- tasty
- http-types
- blaze-html
- wai
- wai-extra
- wai-middleware-static
- optparse-applicative
- katip
- directory
- postgresql-simple
- postgresql-simple-migration
- resource-pool
- exceptions
- data-has


default-extensions:
- NoImplicitPrelude
- OverloadedStrings
- ScopedTypeVariables
- NamedFieldPuns
- TemplateHaskell

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  Snippetbox-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Snippetbox

tests:
  Snippetbox-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Snippetbox
